Kc 49 function refactor
klepsydra-technologies/kpsr-core pull request #76
Opened 2022-02-03 14:38 UTC by hidalgoss

Please, review rebase prior to merge in main.

Steps done were:
git clone kpsr-core repo
git checkout KC-49-function-refactor repo which creates local repo to work in.
git rebase main once HEAD is currectly on KC-49-... repo
Conflict resolution.
Commit 531c3c2 with message "Rebase from main hash f48b623 to KC-49-function-refactor hash 0662e39.".
git config --global push.default current to push current branch only.
git push -f origin KC-49-function-refactor

2022-02-04 14:11 UTC, paulagb8894 requested changes

2022-02-04 14:11 UTC, paulagb8894 commented on core/modules/mem_mdlw/include/klepsydra/mem_core/basic_scheduler.h
> +    void startScheduledTask(const std::string & name,
Remove the spaces (between & and name: &name; and the last space)

2022-02-09 20:04 UTC, pablogh-2000 submitted a review, later dismissed

2022-02-10 09:25 UTC, paulagb8894 submitted a review, later dismissed

2022-02-24 10:10 UTC, pablogh-2000 approved these changes

2022-02-24 10:19 UTC, merged